Please add the assignment operator to hip_bfloat16
ROCm-Developer-Tools/HIP pull request #2303
Opened 2021-07-30 15:24 UTC by neon60

Please add the assignment operator and bool conversion to hip_bfloat16. It would be usefull in rocPRIM and hipCUB.

2021-11-01 15:19 UTC, vince-streamhpc requested changes

2021-11-01 15:19 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +        data = static_cast<_Float16>(x);
_Float16 will not cover whole possible range of bfloat16 correctly

2021-11-01 15:19 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +        data = static_cast<_Float16>(x);
_Float16 will not cover whole possible range of bfloat16 correctly

2021-11-01 15:24 UTC, vince-streamhpc requested changes

2021-11-01 15:24 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +    hip_bfloat16& operator=(T x)
```suggestion
    hip_bfloat16& operator=(const T& x)
```

2021-11-01 15:24 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +    hip_bfloat16& operator=(T x)
```suggestion
    hip_bfloat16& operator=(const T& x)
```

2021-11-09 13:19 UTC, vince-streamhpc requested changes

2021-11-09 13:19 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +    // MANIPULATORS - DEVICE ONLY
comment not applicable?

2021-11-09 13:19 UTC, vince-streamhpc commented on include/hip/hip_bfloat16.h
> +    #if !defined(__HIP_NO_BFLOAT16_CONVERSIONS__)
```suggestion
   
```
merge `#if` statements

2021-12-02 10:22 UTC, neon60 commented
We will change the rocPRIM and we will handle the bfloat16 without the extra assigment operator.

2021-12-02 10:23 UTC, closed without merging