Delete duplicate files - hipify-perl and helper scripts
ROCm-Developer-Tools/HIP pull request #2403
Opened 2021-11-02 17:09 UTC by aakanksha555

SWDEV-309659 - [ROCm QA][IV][QR][G]: hipifyclang package installation fails in the latest builds

hipify-clang package now installs hipify-perl and related helper scripts along with it. https://github.com/ROCm-Developer-Tools/HIPIFY/pull/445

2021-11-02 18:24 UTC, emankov requested changes
There are a lot of places in the HIP repo where hipify-perl and helper scripts are mentioned: documentation, samples, and it looks like all of them have to be cleaned up.
We should get to know what are the new places to refer instead.

2021-11-04 21:15 UTC, aakanksha555 commented
> There are a lot of places in the HIP repo where hipify-perl and helper scripts are mentioned: documentation, samples, and it looks like all of them have to be cleaned up. We should get to know what are the new places to refer instead.

@emankov could you help with any other references I may have missed? I updated link to hipconvertinplace-perl.sh.
hipify package also installs to opt/rocm/hip/bin so can some of the references to $HIP_DIR/bin stay the same?

2021-11-05 12:18 UTC, emankov commented
1. Remove from [Readme.md](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/README.md):
    * **hipify-perl** : Script based tool to convert CUDA code to portable CPP. Converts CUDA APIs and kernel builtins.
    * **hipexamine-perl.sh** : Script to scan the directory, find all code, and report statistics on how much can be ported with HIP (and identify likely features not yet supported).
    * **hipconvertinplace-perl.sh** : Script to scan the directory, find all code, and convert the found CUDA code to HIP reporting all unconverted things.
2. I'd remove [hipify-cmakefile](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/bin/hipify-cmakefile) as well not to mislead. It is a very old, outdated, and incorrect script for hipification. 
3. [README.md](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/samples/0_Intro/square/README.md) in square sample: rename all `/home/user` to `/opt/rocm`.
4. Remove the file https://github.com/ROCm-Developer-Tools/HIP/blob/develop/tests/hipify-clang/unit_tests/libraries/cuSPARSE/cuSPARSE_12.cu

2021-11-05 12:22 UTC, emankov commented
> @emankov could you help with any other references I may have missed? I updated link to hipconvertinplace-perl.sh.
> hipify package also installs to opt/rocm/hip/bin the references to $HIP_DIR/bin would stay the same?

`/opt/rocm/`, `$HIP_DIR`, and `$HIP_PATH` are ok; no changes are needed as long as the HIPIFY tools package is being installed into the same directory as HIP itself.

2021-11-05 16:52 UTC, aakanksha555 commented
> > @emankov could you help with any other references I may have missed? I updated link to hipconvertinplace-perl.sh.
> > hipify package also installs to opt/rocm/hip/bin the references to $HIP_DIR/bin would stay the same?
> 
> `/opt/rocm/`, `$HIP_DIR`, and `$HIP_PATH` are ok; no changes are needed as long as the HIPIFY tools package is being installed into the same directory as HIP itself.

Yep, hipify-clang package installs to /opt/rocm/hip - https://github.com/ROCm-Developer-Tools/HIPIFY/blob/master/CMakeLists.txt#L126

2021-11-05 17:23 UTC, emankov submitted a review, later dismissed
LGTM, but let's wait for the review from Maneesh.

+ Please, make the rest of the requested changes in hip_porting_guide.md.
Thanks!

2021-11-05 17:23 UTC, emankov commented on docs/markdown/hip_porting_guide.md
> -- Use **[bin/hipconvertinplace-perl.sh](https://github.com/ROCm-Developer-Tools/HIP/blob/master/bin/hipconvertinplace-perl.sh)** to hipify all code files in the CUDA source directory.
remove "bin/", please

2021-11-05 17:23 UTC, emankov commented on docs/markdown/hip_porting_guide.md
>  The hipexamine-perl.sh tool will scan a source directory to determine which files contain CUDA code and how much of that code can be automatically hipified.
Add a hyperlink to hipexamine-perl.sh in HIPIFY repo as well, please.

2021-11-05 17:55 UTC, aakanksha555 commented on docs/markdown/hip_porting_guide.md
> -- Use **[bin/hipconvertinplace-perl.sh](https://github.com/ROCm-Developer-Tools/HIP/blob/master/bin/hipconvertinplace-perl.sh)** to hipify all code files in the CUDA source directory.
Done.

2021-11-05 17:55 UTC, aakanksha555 commented on docs/markdown/hip_porting_guide.md
>  The hipexamine-perl.sh tool will scan a source directory to determine which files contain CUDA code and how much of that code can be automatically hipified.
Done.

2021-11-05 17:57 UTC, aakanksha555 commented
> LGTM, but let's wait for the review from Maneesh.
> 
> * Please, make the rest of the requested changes in hip_porting_guide.md.
>   Thanks!

Sure thing. Thanks!

2021-11-06 14:52 UTC, emankov approved these changes

2021-11-08 09:22 UTC, mangupta approved these changes
LGTM

2021-11-09 17:05 UTC, aakanksha555 commented
Thanks, could either of you merge in the changes, I don't have the perms.

2021-11-25 09:42 UTC, merged