SWDEV-289405 - [catch2][dtest][module] Migration of Module files to CATCH2 framework
ROCm-Developer-Tools/HIP pull request #2465
Opened 2022-01-25 06:56 UTC by dkrottap

Migrated all module related files to CATCH2 framework and optimized to
have single module kernel file

Change-Id: I39aa28ef22c1b2f4d0014ca32b59b9c645b725dc

2022-02-07 02:25 UTC, gargrahul approved these changes

2022-02-11 01:06 UTC, gargrahul requested changes

2022-02-11 01:06 UTC, gargrahul commented on tests/catch/include/hip_test_common.hh
> +Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved.
change year to 2021-2022

2022-02-11 01:06 UTC, gargrahul commented on tests/catch/include/hip_test_kernels.hh
> +Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved.
Change year to 2021-2022 as applicable

2022-08-05 03:29 UTC, mangupta commented
This appears to be a duplicate of #2351. Closing it. Please reopen in case it is not a duplicate.

2022-08-05 03:29 UTC, closed without merging