EXSWCPHIPT-138: Update hipHostRegister flag testing
ROCm-Developer-Tools/HIP pull request #2835
Opened 2022-08-01 14:30 UTC by fabiomestre

2022-08-01 14:46 UTC, FMarno requested changes

2022-08-01 14:46 UTC, FMarno commented on tests/catch/unit/memory/hipHostRegister.cc
> +    size_t memFree = (std::min)(devMemFree, hostMemFree);  // which is the limiter cpu or gpu
```suggestion
    size_t memFree = std::min(devMemFree, hostMemFree);  // which is the limiter cpu or gpu
```

2022-08-01 20:20 UTC, chrispaquot approved these changes, later dismissed

2022-08-02 14:03 UTC, FMarno requested changes

2022-08-02 14:03 UTC, FMarno commented on tests/catch/unit/memory/hipHostRegister.cc
> +  TestType* hostPtr = reinterpret_cast<TestType*>(malloc(sizeBytes));
`hostPtr` is not freed

2022-08-03 11:20 UTC, merged