fix logic for finding nvcc even if clang exists
ROCm-Developer-Tools/HIP pull request #2849
Opened 2022-08-06 13:56 UTC by acxz

Issue: if a system has both `nvcc` and `clang++` (compiled w/o amd) then the HIP-PLATFORM autodetects to `amd`, instead of `nvidia`.

this PR fixes it by only checking for `clang++` compiled with amd.

Follow up of https://github.com/ROCm-Developer-Tools/HIP/pull/2623

Fixes: https://github.com/ROCm-Developer-Tools/HIP/issues/1650

Fixes comment: https://github.com/ROCm-Developer-Tools/HIP/issues/2256#issuecomment-818801109

2022-08-10 12:13 UTC, scchan requested changes

2022-08-10 12:13 UTC, scchan commented on bin/hipvars.pm
> -    if (can_run("$HIP_CLANG_PATH/clang++") or can_run("clang++")) {
I'd suggest changing it to `can_run(amdclang++)`, which is an alias to AMD's version of clang.
I'd recommend to our HIP team to run a more extensive set of tests to see if any app breaks due to this dependence

2022-08-10 13:32 UTC, acxz commented on bin/hipvars.pm
> -    if (can_run("$HIP_CLANG_PATH/clang++") or can_run("clang++")) {
What is the path of `amdclang++`? I don't seem to have that alias when I build rocm-llvm.

In any case, this PR is simply an atomic change removing system clang++. For changing `HIP_CLANG_PATH/clang++` you should open up another PR and I can rebase off of it.

2022-08-17 18:10 UTC, acxz commented on bin/hipvars.pm
> -    if (can_run("$HIP_CLANG_PATH/clang++") or can_run("clang++")) {
Looking at your comment again, I understand what you meant now, basically replacing `clang++` with `amdclang++`.

2022-08-17 18:13 UTC, acxz commented on bin/hipvars.pm
> -    if (can_run("$HIP_CLANG_PATH/clang++") or can_run("clang++")) {
Added your suggestion!

2023-10-31 10:23 UTC, Snektron commented
Can this be merged yet?

2023-10-31 11:47 UTC, mangupta commented
@Snektron : hipcc and corresponding dependencies such as hipvars.pm have been moved out of the hip repo. See #3216. These scripts are now part of the [hipcc project](https://github.com/ROCm-Developer-Tools/hipcc/).

2023-12-11 03:46 UTC, acxz commented
Thanks for mentioning that @mangupta
Closing this PR in favor of https://github.com/ROCm/HIPCC/pull/145

2023-12-11 03:46 UTC, closed without merging